version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: database
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend-server:
    build: .
    container_name: backend-server
    depends_on:
      - database
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - ".:/src"
      - /src/node_modules
    command: ./wait-for-postgres.sh

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
