version: '3.8'

services:
  backend-server:
    build: .
    container_name: backend-server
    ports:
      - "8080:8080"
    volumes:
      - ".:/src"
    command: npm run dev
    environment:
      - NODE_ENV=development
    
  db:
    image: postgres:latest
    container_name: database
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: